name: stig-checks
on: [push]
jobs:
  stig-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: STIG checks - SCM
        run: |
          echo "Running STIG checks against artifacts in Git repo"
          ./run_inspec.sh
      - name: Build image
        run: echo "Building image"
      - name: STIG checks - Image build
        run: echo "Running STIG checks against image"
      - name: Generate deployment configuration
        run: echo "Generating deployment configuration"
      - name: STIG checks - Deployment configuration
        run: echo "Running STIG checks against deployment configuration"
      - name: Deploy container
        run: echo "Deploying container"
      - name: STIG checks - Running container
        run: echo "Running STIG checks deployed container"
      - name: STIG Report
        run: echo "STIG report for container-id"
